imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
    translator: { fallback: en }
    
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

lyra_admin:
    models:
        listing:
            class: 'Acme\ClassifiedsBundle\Entity\Listing'
            list:
                title: Listings
                columns:
                    ad_title: ~
                    published: ~
                    posted_at: ~
        location:
            class: 'Acme\ClassifiedsBundle\Entity\Location'
            list:
                title: Locations
                columns:
                    title: ~
                    address: ~
                    zip: ~                    
                    city: ~
                    country: ~
                    localization: ~   
        product:
            class: 'Acme\ClassifiedsBundle\Entity\Product'
            list:
                title: Products
                columns:
                    ad_title: ~                    
                    name: ~
                    category: ~
                    ad_title: ~
                    published: ~
                    posted_at: ~       
        category:
            class: 'Acme\ClassifiedsBundle\Entity\Category'
            list:
                title: Category
                columns:
                    ad_title: ~                    
                    published: ~      